# Generated by Django 6.0.4 on 2026-04-28 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Categorie',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CourseMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'Janvier'), (2, 'Fevrier'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Aout'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Decembre')])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='months', to='courses.category')),
            ],
            options={
                'verbose_name': 'Mois de cours',
                'verbose_name_plural': 'Mois de cours',
                'ordering': ['category__name', 'month'],
                'unique_together': {('category', 'month')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.coursemonth'),
        ),
    ]
