# Generated by Django 6.0.4 on 2026-04-29 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_subscriptionpricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='courses.category'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='courses.coursemonth'),
        ),
    ]
