# Generated by Django 6.0.4 on 2026-05-01 15:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_subscription_category_subscription_month'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursemonth',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['level'], name='courses_course_level_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['created_at'], name='courses_course_created_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['month', 'title'], name='courses_course_month_title_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['course', 'enrolled_at'], name='courses_enroll_course_date_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['course', 'position'], name='courses_lesson_course_pos_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'end_at'], name='courses_sub_user_end_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'plan', 'category', 'month', 'end_at'], name='courses_sub_access_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['category', 'plan', 'end_at'], name='courses_sub_cat_plan_end_idx'),
        ),
        migrations.AddConstraint(
            model_name='coursemonth',
            constraint=models.UniqueConstraint(fields=('category', 'month'), name='courses_coursemnth_category_month_uniq'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('course', 'email'), name='courses_enroll_course_email_uniq'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('course', 'position'), name='courses_lesson_course_position_uniq'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('end_at__gte', models.F('start_at'))), name='courses_sub_end_after_start_chk'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('month__isnull', False), ('plan', 'monthly')), models.Q(('month__isnull', True), ('plan', 'yearly')), _connector='OR'), name='courses_sub_plan_month_consistency_chk'),
        ),
    ]
