# Generated by Django 6.0.4 on 2026-05-01 22:23

from django.conf import settings
from django.db import migrations, models


def approve_existing_subscriptions(apps, schema_editor):
    Subscription = apps.get_model("courses", "Subscription")
    Subscription.objects.all().update(trainer_approved=True)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_coursemonth_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='trainer_approved',
            field=models.BooleanField(default=False, help_text="Si faux, l'etudiant ne peut pas acceder au contenu reserve malgre les dates.", verbose_name='Valide par le formateur'),
        ),
        migrations.RunPython(approve_existing_subscriptions, noop_reverse),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['trainer_approved', 'end_at'], name='courses_sub_approved_end_idx'),
        ),
    ]
