# Generated by Django 6.0.4 on 2026-05-01 22:45

from django.db import migrations, models


def mark_existing_enrollments_validated(apps, schema_editor):
    Enrollment = apps.get_model("courses", "Enrollment")
    for enrollment in Enrollment.objects.filter(trainer_validated=False).iterator():
        enrollment.trainer_validated = True
        enrollment.validated_at = enrollment.enrolled_at
        enrollment.save(update_fields=["trainer_validated", "validated_at"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_subscription_trainer_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant (inscription)'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='trainer_validated',
            field=models.BooleanField(default=False, verbose_name='Inscription validee par le formateur'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(mark_existing_enrollments_validated, noop_reverse),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['trainer_validated', 'validated_at'], name='courses_enroll_validated_idx'),
        ),
    ]
