# Generated by Django 6.0.4 on 2026-05-03 00:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_enrollment_trainer_validation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='trainer_rejected',
            field=models.BooleanField(default=False, help_text="Si vrai, la demande est refusee ; l'etudiant peut soumettre une nouvelle demande.", verbose_name='Refuse par le formateur'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['trainer_rejected', 'end_at'], name='courses_sub_rejected_end_idx'),
        ),
    ]
