# Generated by Django 6.0.4 on 2026-05-08 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_coursequizquestion_correct_indices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('note_sur_20', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('passed_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='courses.course')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='courses.coursemonth')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_exam_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resultat examen mensuel',
                'verbose_name_plural': 'Resultats examens mensuels',
                'ordering': ['month__category__name', 'month__month', '-note_sur_20', 'user__last_name', 'user__first_name'],
                'indexes': [models.Index(fields=['month', '-note_sur_20'], name='courses_exres_m_note_idx'), models.Index(fields=['user', 'month'], name='courses_exres_u_m_idx')],
                'constraints': [models.UniqueConstraint(fields=('month', 'user'), name='courses_exres_m_u_uniq')],
            },
        ),
    ]
