# Generated by Django 6.0.5 on 2026-05-09 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_monthlyexamresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Examen mensuel', max_length=200)),
                ('description', models.TextField(blank=True, help_text="Description de l'examen")),
                ('questions', models.JSONField(default=list, help_text='Liste des questions au format JSON')),
                ('passing_score', models.PositiveIntegerField(default=12, help_text='Note sur 20 pour réussir')),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='Durée en minutes')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='courses.coursemonth')),
            ],
            options={
                'verbose_name': 'Examen mensuel',
                'verbose_name_plural': 'Examens mensuels',
                'ordering': ['month__category__name', 'month__month'],
            },
        ),
    ]
