# Generated by Django 6.0.4 on 2026-05-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_monthlyexam'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyexam',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='PDF pour générer les questions automatiquement', null=True, upload_to='exam_pdfs/'),
        ),
    ]
