# Generated by Django 6.0.4 on 2026-05-09 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_monthlyexam_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyexam',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='courses.coursemonth'),
        ),
        migrations.AlterField(
            model_name='monthlyexamresult',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='courses.course'),
        ),
    ]
