# Generated by Django 6.0.4 on 2026-05-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_remove_monthlyexamresult_courses_exres_m_u_uniq'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='content_type',
            field=models.CharField(choices=[('subject', 'Sujet'), ('correction', 'Correction')], default='subject', max_length=20),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['month', 'content_type', 'title'], name='courses_month_type_title_idx'),
        ),
    ]
